import { pat, titleLabel } from '../styles.js';
import type { Franchise, Group } from '../types.js';

const phase = (n: number, name: string, color: string): Group => ({ num: String(n), name, color, pattern: pat.dots(color) });

/**
 * Release order, Phases as seasons. A show's seasons are split where release
 * order interleaves them (Loki S2 after Secret Invasion). Titles announced but
 * not out yet are listed now and appear once released.
 */
export const mcu: Franchise = {
  id: 'mcu',
  name: 'MCU · Watch Order',
  style: 'mcu',
  releaseInfo: '2008–',
  description: 'Every MCU film and show in release order, seasons split where the story needs it. Seasons are the Phases. Watch the X-Men playlist before Deadpool & Wolverine.',
  poster: 'https://images.metahub.space/poster/medium/tt4154796/img',
  background: 'https://images.metahub.space/background/medium/tt4154796/img',
  logo: { accent: 'MCU', rest: 'Watch Order' },
  groups: {
    1: phase(1, 'Phase One', '#c8102e'),
    2: phase(2, 'Phase Two', '#c9971c'),
    3: phase(3, 'Phase Three', '#6a3fb5'),
    4: phase(4, 'Phase Four', '#2f8f5b'),
    5: phase(5, 'Phase Five', '#e0572a'),
    6: phase(6, 'Phase Six', '#2b6cd4'),
  },
  plan: [
    [1, [
      { movie: 'tt0371746', title: 'Iron Man' },
      { movie: 'tt0800080', title: 'The Incredible Hulk' },
      { movie: 'tt1228705', title: 'Iron Man 2' },
      { movie: 'tt0800369', title: 'Thor' },
      { movie: 'tt0458339', title: 'Captain America: The First Avenger', short: 'The First Avenger' },
      { movie: 'tt0848228', title: 'The Avengers' },
    ]],
    [2, [
      { movie: 'tt1300854', title: 'Iron Man 3' },
      { movie: 'tt1981115', title: 'Thor: The Dark World', short: 'The Dark World' },
      { movie: 'tt1843866', title: 'Captain America: The Winter Soldier', short: 'The Winter Soldier' },
      { movie: 'tt2015381', title: 'Guardians of the Galaxy' },
      { series: 'tt3475734', seasons: [1,2], title: 'Agent Carter' },
      { movie: 'tt2395427', title: 'Avengers: Age of Ultron', short: 'Age of Ultron' },
      { movie: 'tt0478970', title: 'Ant-Man' },
    ]],
    [3, [
      { movie: 'tt3498820', title: 'Captain America: Civil War', short: 'Civil War' },
      { movie: 'tt1211837', title: 'Doctor Strange' },
      { movie: 'tt3896198', title: 'Guardians of the Galaxy Vol. 2', short: 'Guardians Vol. 2' },
      { movie: 'tt2250912', title: 'Spider-Man: Homecoming', short: 'Spider-Man: Homecoming' },
      { movie: 'tt3501632', title: 'Thor: Ragnarok', short: 'Ragnarok' },
      { movie: 'tt1825683', title: 'Black Panther' },
      { movie: 'tt4154756', title: 'Avengers: Infinity War', short: 'Infinity War' },
      { movie: 'tt5095030', title: 'Ant-Man and the Wasp', short: 'Ant-Man & the Wasp' },
      { movie: 'tt4154664', title: 'Captain Marvel' },
      { movie: 'tt4154796', title: 'Avengers: Endgame', short: 'Endgame' },
      { movie: 'tt6320628', title: 'Spider-Man: Far From Home', short: 'Far From Home' },
    ]],
    [4, [
      { series: 'tt9140560', seasons: [1], title: 'WandaVision' },
      { series: 'tt9208876', seasons: [1], title: 'The Falcon and the Winter Soldier', short: 'Falcon & Winter Soldier' },
      { series: 'tt9140554', seasons: [1], title: 'Loki' },
      { movie: 'tt3480822', title: 'Black Widow' },
      { series: 'tt10168312', seasons: [1], title: 'What If...?' },
      { movie: 'tt9376612', title: 'Shang-Chi and the Legend of the Ten Rings', short: 'Shang-Chi' },
      { movie: 'tt9032400', title: 'Eternals' },
      { series: 'tt10160804', seasons: [1], title: 'Hawkeye' },
      { movie: 'tt10872600', title: 'Spider-Man: No Way Home', short: 'No Way Home' },
      { series: 'tt10234724', seasons: [1], title: 'Moon Knight' },
      { movie: 'tt9419884', title: 'Doctor Strange in the Multiverse of Madness', short: 'Multiverse of Madness' },
      { series: 'tt10857164', seasons: [1], title: 'Ms. Marvel' },
      { movie: 'tt10648342', title: 'Thor: Love and Thunder', short: 'Love and Thunder' },
      { series: 'tt13623148', seasons: [1], title: 'I Am Groot' },
      { series: 'tt10857160', seasons: [1], title: 'She-Hulk: Attorney at Law', short: 'She-Hulk' },
      { movie: 'tt15318872', title: 'Werewolf by Night' },
      { movie: 'tt9114286', title: 'Black Panther: Wakanda Forever', short: 'Wakanda Forever' },
      { movie: 'tt13623136', title: 'The Guardians of the Galaxy Holiday Special', short: 'Holiday Special' },
    ]],
    [5, [
      { movie: 'tt10954600', title: 'Ant-Man and the Wasp: Quantumania', short: 'Quantumania' },
      { movie: 'tt6791350', title: 'Guardians of the Galaxy Vol. 3', short: 'Guardians Vol. 3' },
      { series: 'tt13157618', seasons: [1], title: 'Secret Invasion' },
      { series: 'tt13623148', seasons: [2], title: 'I Am Groot' },
      { series: 'tt9140554', seasons: [2], title: 'Loki' },
      { movie: 'tt10676048', title: 'The Marvels' },
      { series: 'tt10168312', seasons: [2], title: 'What If...?', optional: true },
      { series: 'tt13966962', seasons: [1], title: 'Echo' },
      { movie: 'tt6263850', title: 'Deadpool & Wolverine', note: 'Best after the X-Men order.' },
      { series: 'tt15571732', seasons: [1], title: 'Agatha All Along' },
      { series: 'tt10168312', seasons: [3], title: 'What If...?', optional: true },
      { series: 'tt16027074', seasons: [1], title: 'Your Friendly Neighborhood Spider-Man', short: 'Friendly Neighborhood' },
      { movie: 'tt14513804', title: 'Captain America: Brave New World', short: 'Brave New World' },
      { series: 'tt3322312', seasons: [1,2,3], title: 'Daredevil', note: 'Netflix catch-up before Born Again.' },
      { series: 'tt5675620', seasons: [1,2], title: 'The Punisher', note: 'Netflix catch-up before Born Again.' },
      { series: 'tt18923754', seasons: [1], title: 'Daredevil: Born Again', short: 'Born Again' },
      { movie: 'tt20969586', title: 'Thunderbolts*' },
      { series: 'tt13623126', seasons: [1], title: 'Ironheart' },
    ]],
    [6, [
      { movie: 'tt10676052', title: 'The Fantastic Four: First Steps', short: 'Fantastic Four' },
      { series: 'tt13968252', seasons: [1], title: 'Eyes of Wakanda' },
      { series: 'tt16027014', seasons: [1], title: 'Marvel Zombies' },
      { series: 'tt21066182', seasons: [1], title: 'Wonder Man' },
      { series: 'tt18923754', seasons: [2], title: 'Daredevil: Born Again', short: 'Born Again' },
      { movie: 'tt36042156', title: 'The Punisher: One Last Kill', short: 'One Last Kill' },
      { movie: 'tt22084616', title: 'Spider-Man: Brand New Day', short: 'Brand New Day' },
      { movie: 'tt21357150', title: 'Avengers: Doomsday', short: 'Doomsday' },
      { movie: 'tt21361444', title: 'Avengers: Secret Wars', short: 'Secret Wars' },
    ]],
  ],
  label: titleLabel({ word: 'Phase', numOf: String }),
};
